---
title: "2-vaPrcoessing"
author: "Will Sheppard"
date: "2024-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
This function takes a list of the required packages, checks if they are installed, downloads those that are not, and then loads them.

```{r packages, warning=FALSE}

requiredPackages = c("tidyverse", "quickpsy")
for(p in requiredPackages){
  if(!require(p,character.only = TRUE)) install.packages(p)
  library(p,character.only = TRUE)
}

```

read data 
```{r read data}
data <- read.csv("../savedData/vaSumm.csv")

```

The Bland-Altman analysis had the greatest levels of agreement when VA thresholds were estimated with a logistic function and a 1/26 lapse rate. 
```{r va maodelling}

cols <- c("id",
          "va", "vaLower", "vaUpper",
          "percCorrect","fun", "guessRate",
          "condition")



#funList <- c("logistic_fun", "cum_normal_fun", "weibull_fun")
funList <- c("logistic_fun")

denomList <- c(26)

conditionList <- c("blur", "clear")

for (cond in conditionList) {
  
  conditionData <- data %>%
    filter(condition == cond)
      
      pplist <- unique(conditionData$id)
      #pplist <- 1:10
      
      thresh <- data.frame(matrix(
      data = NA,
      nrow = length(pplist),
      ncol = 8))
      
      colnames(thresh) <- cols
      
      for (fun in funList) {
        for (denom in denomList) {
          for (pp in pplist) {
            
            d <- conditionData %>%
              filter(id == pp)
            
            g <- 1/denom
            p <- g + .5 * (1 - g)
            
            xMIN <- min(d$logMAR)
            xMAX <- max(d$logMAR)+0.1
            
            minPercCorr = min(d$percCorrect)
            minLogMAR = min(d$logMAR)
            
            print(paste("Participant:", pp, " ", cond, "", ", ", fun, "", ", Guess rate: 1/", denom, sep = ""))
            
            if (minPercCorr < p) {
              if (fun == "logistic_fun"){
                fitOne <- quickpsy(d = d, x = logMAR, k = totalCorrect, n = totalAttempt,
                               guess = g, lapses = TRUE, bootstrap = 'nonparametric',
                               xmin = xMIN, xmax = xMAX, fun = logistic_fun)
              }else if (fun == "cum_normal_fun"){
                fitOne <- quickpsy(d = d, x = logMAR, k = totalCorrect, n = totalAttempt,
                               guess = g, lapses = TRUE, bootstrap = 'nonparametric',
                               xmin = xMIN, xmax = xMAX, fun = cum_normal_fun)
              }else if (fun == "weibull_fun"){
                
                d$logMAR <- d$logMAR+0.2
                
                xMIN <- min(d$logMAR)
                xMAX <- max(d$logMAR)+0.1
                
                fitOne <- quickpsy(d = d, x = logMAR, k = totalCorrect, n = totalAttempt,
                               guess = g, lapses = TRUE, bootstrap = 'nonparametric',
                               xmin = xMIN, xmax = xMAX, fun = weibull_fun)
              }
              
              x <- plotcurves(fitOne)+
              scale_x_continuous(limits = c(xMIN, xMAX), breaks = seq(-0.2, xMAX, 0.1))+
              scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.1))+
              ggtitle(paste("pp: ", pp, " - ", cond, ", ", fun, "guess rate 1/", denom))
              show(x)
            
              thresh[which(pplist == pp), 1] <- pp
              thresh[which(pplist == pp), 2] <- round(fitOne$thresholds[1], digits = 2)
              thresh[which(pplist == pp), 3] <- round(fitOne$thresholds[3], digits = 2)
              thresh[which(pplist == pp), 4] <- round(fitOne$thresholds[4], digits = 2)
              thresh[which(pplist == pp), 5] <- fitOne$thresholds[2]
              thresh[which(pplist == pp), 6] <- fun
              thresh[which(pplist == pp), 7] <- 1/denom
              thresh[which(pplist == pp), 8] <- cond
            
            } else{
              if(fun == "weibull_fun"){
                thresh[which(pplist == pp), 1] <- pp
                thresh[which(pplist == pp), 2] <- xMIN+0.2
                thresh[which(pplist == pp), 3] <- xMIN+0.2
                thresh[which(pplist == pp), 4] <- xMIN+0.2
                thresh[which(pplist == pp), 5] <- p
                thresh[which(pplist == pp), 6] <- fun
                thresh[which(pplist == pp), 7] <- 1/denom
                thresh[which(pplist == pp), 8] <- cond
              }else{
                thresh[which(pplist == pp), 1] <- pp
                thresh[which(pplist == pp), 2] <- xMIN
                thresh[which(pplist == pp), 3] <- xMIN
                thresh[which(pplist == pp), 4] <- xMIN
                thresh[which(pplist == pp), 5] <- p
                thresh[which(pplist == pp), 6] <- fun
                thresh[which(pplist == pp), 7] <- 1/denom
                thresh[which(pplist == pp), 8] <- cond
              }
              
                
            }
              
            
            
          }
          assign(paste(fun, denom, "va", cond, sep = ""), thresh)
        }
      }
  
}

vaThresh <- bind_rows(logistic_fun26vablur, logistic_fun26vaclear)
```

```{r save va data}

write.csv(vaThresh, "../savedData/vaThreshold.csv")
```