---
title: "visualSummaryStats"
author: "Will Sheppard"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(tidyverse)
library(car)
```

```{r read data}

cs <- read.csv("../cleanData/csThresh.csv")
va <- read.csv("../cleanData/vaThresh.csv")

va <- va %>% rename(VA = threshold)
```

CS and VA data are bimodally distributed. Non-paremetric measures should be used

```{r distributions}

ggplot(cs, aes(x = CS, fill = condition, color = condition))+
  geom_density(alpha = 0.4)

ggplot(va, aes(x = VA, fill = condition, color = condition))+
  geom_density(alpha = 0.4)



```

```{r bimodal}
demo <- read.csv("../data/data_exp_62188-v20_questionnaire-e2l7.csv")%>%
  filter(Question.Key == 'age_in_years ')%>%
  dplyr::select(Participant.Private.ID, Response)%>%
  rename(age = Response)%>%
  rename(id = Participant.Private.ID)

ppList <- unique(demo$id)

demo <- demo %>%
  filter(id %in% ppList)

cs <- cs %>%
  filter(id %in% ppList)

nrows <- length(cs$id)

cs$age <- NA

for (row in 1:nrows) {

  cs$age[row] <-  as.numeric(demo$age[which(demo$id == cs[row,1])])
}

vaRows <- length(va$Participant.Private.ID)
va$age <- NA

va <- va %>%
  filter(Participant.Private.ID %in% ppList)

for (row in 1:nrows) {

  va$age[row] <-  as.numeric(demo$age[which(demo$id == va[row,1])])
}

va <- va  %>%
  mutate(old = case_when(
    age > mean(age) ~ 'old',
    TRUE ~ 'young'
  ))

ggplot(cs, aes(x = age, y = CS, color = condition))+
  geom_point()

cs <- cs %>%
  mutate(old = case_when(
    age > mean(age) ~ 'old',
    TRUE ~ 'young'
  ))

ggplot(cs, aes(x = CS, fill = condition, color = condition))+
  geom_density(alpha = 0.4)+
  facet_grid(~old)

ggplot(cs, aes(x = old, group = old, y = CS))+
  geom_boxplot()+
  facet_grid(~condition)

```

```{r cs clean}

csImp  <- cs %>%
  filter(condition == 'clear')%>%
  mutate(csImp = case_when(
    CS < 1.5 ~ 1,
    TRUE ~ 0
  ))%>%
  filter(csImp == 1)

```

```{r csSumamry}
csSumm <- cs %>%
  group_by(condition)%>%
  summarise(meanCS = mean(CS),
            sdCS = sd(CS),
            minCS = min(CS),
            maxCS = max(CS)
            )
```




```{r vaSumamry}
vaSumm <- va %>%
  group_by(condition)%>%
  summarise(meanVA = mean(VA),
            sdVA = sd(VA),
            minVA = min(VA),
            maxVA = max(VA)
            )
```

```{r wilcoxTest}

csClear <- subset(cs, condition == 'clear', CS, drop = T)
csBlur <- subset(cs, condition == 'blur', CS, drop = T)

vaClear <- subset(va, condition == 'clear', VA, drop = T)
vaBlur <- subset(va, condition == 'blur', VA, drop = T)

wilcox.test(csClear, csBlur, paired = T)
wilcox.test(vaClear, vaBlur, paired = T)

```

```{r pairedPlots}
library(PairedData)
csClear <- subset(cs, condition == 'clear', CS, drop = T)
csBlur <- subset(cs, condition == 'blur', CS, drop = T)

csPair <- paired(csClear, csBlur)

plot(csPair, type = 'profile')

ggplot(cs, aes(y = CS, group = condition, ))+
  geom_boxplot()

```

```{r cs plot}


cols <- c('old' = 'black', 'young' = 'grey')
shapes <- c('old' = 24, 'young' = 25)

csViolin <- ggplot(cs, mapping = aes(x = condition, y = CS)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(height = 0, width = 0.2, alpha = .6, aes(color = old, shape = old, fill = old))+
  scale_color_manual(values = cols,
                     aesthetics = c('color', 'fill'),
                     labels = c('over 30', 'under 30'))+
  scale_shape_manual(values = shapes,
                     labels = c('over 30', 'under 30')) + 
  scale_x_discrete(labels = c("Monocular blur", "No blur"))+
  theme(legend.title = element_blank(),
        axis.title.x.bottom = element_blank())

csViolin <- ggplot(cs, mapping = aes(x = condition, y = CS)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(height = 0, width = 0.2, alpha = .6, aes(color = age, fill = age))+
  scale_color_gradient(low = "lightgrey",
                        high = "black")+
  scale_fill_gradient(low = "lightgrey",
                        high = "black")+
  scale_x_discrete(labels = c("Monocular blur", "No blur"))+
  theme(#legend.title = element_blank(),
        axis.title.x.bottom = element_blank())+
  labs(color = "Age (years)",
       fill = "Age (years)")

show(csViolin)


```

```{r save cs plot}

dpi = 800
h = 4
w = 7

ggsave('../figures/csViolin.png',
       plot = csViolin,
       dpi = dpi,
       width = w,
       height = h)

```


```{r cs mlm}
library(nlme)

mlmCS <- cs %>%
  mutate(condition = case_when(
    condition == 'clear' ~ 0,
    TRUE ~ 1
  ))

csMLM <- lme(CS ~ condition + age, 
             data = mlmCS, 
             random = ~id|id,
             method = 'ML')
summary(csMLM)
csModelComp <- intervals(csMLM, which = 'fixed')
csModelComp

```

```{r va violin}


vaViolin <- ggplot(va, mapping = aes(x = condition, y = VA)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(height = 0, width = 0.2, alpha = .6, aes(color = age, fill = age))+
  scale_color_gradient(low = "lightgrey",
                        high = "black")+
  scale_fill_gradient(low = "lightgrey",
                        high = "black")+
  scale_x_discrete(labels = c("Monocular blur", "No blur"))+
  theme(#legend.title = element_blank(),
        axis.title.x.bottom = element_blank())+
  labs(color = "Age (years)",
       fill = "Age (years)")

show(vaViolin)
```

```{r save va plot}

# parameters in save cs plot

ggsave('../figures/vaViolin.png',
       plot = vaViolin,
       dpi = dpi,
       width = w,
       height = h)

```

```{r va mlm}

mlmVA <- va %>%
  mutate(condition = case_when(
    condition == 'clear' ~ 0,
    TRUE ~ 1
  ))

vaMLM <- lme(VA ~ condition + age, 
             data = mlmVA, 
             random = ~Participant.Private.ID|Participant.Private.ID,
             method = 'ML')
summary(vaMLM)
vaModelComp <- intervals(vaMLM, which = 'fixed')
vaModelComp

# AIC = -241.1912

```

```{r va alt models}
library(lme4)

# can't add random slope - too many parameters
vaGaussian <- lmer(VA ~ condition + age + (1|Participant.Private.ID),
                   data = mlmVA)
summary(vaGaussian)
vaGausModComp <- intervals(vaGaussian)

AIC(vaGaussian)
# -217.5842
# can't use gamma due to non-zero values
vaGamma <- glmer(VA ~ condition + age + (1|Participant.Private.ID),
                 family = Gamma(link = "identity"),
                   data = mlmVA)

# can't use inverse gausian due to negative values
vaIG <- glmer(VA ~ condition + age + (1|Participant.Private.ID),
                 family = inverse.gaussian(link = "identity"),
                   data = mlmVA)

```

```{r cs alt models}
# current model has AIC = -96.43892	
csGaussian <- lmer(CS ~ condition + age + (1|id),
                   data = mlmCS)
summary(csGaussian)
AIC(csGaussian)
# - 77

csGamma<- glmer(CS ~ condition + age + (1|id),
                 family = Gamma(link = "identity"),
                   data = mlmCS)
summary(csGamma)
fixef(csGamma)
AIC(csGamma)
# -154.8879

csGamma_coefs <- summary(csGamma)

intLow <- csGamma_coefs$coefficients[1,1]-1.96*csGamma_coefs$coefficients[1,2]
intHigh <- csGamma_coefs$coefficients[1,1]+1.96*csGamma_coefs$coefficients[1,2]

condLow <- csGamma_coefs$coefficients[2,1]-1.96*csGamma_coefs$coefficients[2,2]
condHigh <- csGamma_coefs$coefficients[2,1]+1.96*csGamma_coefs$coefficients[2,2]

ageLow <- csGamma_coefs$coefficients[3,1]-1.96*csGamma_coefs$coefficients[3,2]
ageHigh <- csGamma_coefs$coefficients[3,1]+1.96*csGamma_coefs$coefficients[3,2]

csIG <- glmer(CS ~ condition + age + (1|id),
                 family = inverse.gaussian(link = "identity"),
                   data = mlmCS)
summary(csIG)
AIC(csIG)
# -147
```